// @ts-check

/** @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarItemConfig[]} */
const apiMenu = [
  {
    type: 'autogenerated',
    dirName: 'api',
  },
];

/** @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarItemConfig[]} */
const guidesMenu = [
  {
    type: 'autogenerated',
    dirName: 'guides',
  },
];

/** @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarItemConfig[]} */
const overviewMenu = [
  {
    type: 'doc',
    id: 'overview',
  },
  {
    type: 'autogenerated',
    dirName: 'main',
  },
];

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // But you can create a sidebar manually

  overview: overviewMenu,
  guides: guidesMenu,
  api: apiMenu,
};

module.exports = sidebars;
